# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-11 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('desc', models.CharField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(height_field=190, upload_to='booksimage', width_field=190)),
                ('documentNumber', models.CharField(max_length=15)),
                ('idNumber', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('lang', models.CharField(blank=True, max_length=20, null=True)),
                ('info', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('avaiable', 'Available'), ('out', 'out')], default='available', max_length=8)),
                ('backDate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Category'),
        ),
    ]
