# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-15 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_book_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='backDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishdate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('available', 'Available'), ('out', 'out')], default='available', max_length=10),
        ),
    ]
