# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-15 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_auto_20190815_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='backDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
