# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-17 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0008_auto_20190817_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.User')),
            ],
        ),
    ]
